--In this SQL is one column.
--Modify this SQL each word must be column who is separated with '^'
SELECT 
'DENUMIRE^CUI^COD_INMATRICULARE^EUID^STARE_FIRMA^ADRESA_COMPLETA^ADR_TARA^ADR_LOCALITATE^ADR_JUDET^ADR_DEN_STRADA^ADR_DEN_NR_STRADA^ADR_BLOC^ADR_SCARA^ADR_ETAJ^ADR_APARTAMENT^ADR_COD_POSTAL^ADR_SECTOR^ADR_COMPLETARE' AS  TEXT
FROM DUAL
